### ISSUE TITLE
vuxenutbildning.malmo.se i GA

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#11]
GA  betraktar startsidan för subdomänen som samma sida som startsidan för malmo.se. Övriga sidor på subdomänen kan identifieras i GA, men alltså inte startsidan. 

Är det en felaktig konfiguration eller måste vi göra en work around?

**Comment by martent** [comment]
Det beror på att hostname inte visas i rapporterna som finns, endast request path. Tjänster med olika subdomäner går då inte att skilja om de har samma request path, t.ex. `/`. Detta kommer att öka när ni övergår till er nya subdomänstandard.

Det finns tre fyra sätt att ställa in detta i Google Analytics beroende på vad man vill ha ut.

1. Vill man ha ut sidans fulla adress där både hostname och request path inkluderas sätter man upp ett filter för kontot. Jag har satt upp ett för malmo.se-test och du kan se hur URL:erna ser ut om du kollar på kontot www.test.malmo.se för dagens trafik. FiItret jag satte upp ser du under Admin för www.test.malmo.se i View-kolumnen under Filters. Jag har kallat visningsfiltret "Prepend hostname to request path". Det tar några timmar innan ett filter slår igenom.
1. Vill du tillfälligt visa både request path och hostname kan du antingen:
    1. sätta Hostname som primärt filter och Page som sekundärt. 
    1. Eller omvänt.
1. Vill man ha ut olika webbtjänster i olika rapporter lägger man till "include only" och väljer "hostname" och anger hostname för tjänsten.

Bilder på hur det då ser ut i webbvyer och filterinställningar

## Prepend hostname to request path
<img width="685" alt="prepend hostname to request path" src="https://cloud.githubusercontent.com/assets/603695/20600635/e470c6d6-b254-11e6-8a5b-0519c3eefe66.png">

## Hostname as primary dimension and page as secondary
<img width="512" alt="hostname as primary dimension and page as secondary" src="https://cloud.githubusercontent.com/assets/603695/20600633/e46fe46e-b254-11e6-8818-e44c81baf820.png">

## Hostname as secondary dimension
<img width="497" alt="host name as secondary dimension" src="https://cloud.githubusercontent.com/assets/603695/20600634/e470c5fa-b254-11e6-9703-2296dbc7b00e.png">

## Report excluding a subdomain
<img width="1061" alt="report excluding a subdomain" src="https://cloud.githubusercontent.com/assets/603695/20600636/e4718440-b254-11e6-9d56-654785e0ea2b.png">

**Comment by olajoh1** [comment]
Skapade ett filer enligt förslag 1. Det löser ett problem men skapar ett annat. Den statistik som redan rapporterats in uppdateras inte host. Tror det finns en möjlighet att göra det retroaktivt?

![image](https://cloud.githubusercontent.com/assets/6176181/23546242/f2c26328-fffe-11e6-9eb8-e35ee5d8653e.png)

**Comment by martent** [comment]
Alternativ 1 verkar endast påverka inkommande data:

> Filters cannot be applied to your previous historical data; they can only be applied to your data moving forward. 
http://www.lunametrics.com/blog/2015/12/10/basic-google-analytics-filters/

Ny data sparas filtrerat:

> Filters are destructive. Filtering your incoming hits permanently changes those hits in that view, according to the type of filter. Therefore, you should ALWAYS maintain an unfiltered view of your data.
https://support.google.com/analytics/answer/1033162?hl=en

Alternativ 2 och 3 borde fungera på befintlig ofiltrerad data.

**Comment by magnivar** [comment]
Ola säger: LÖST
