### ISSUE TITLE
Besök rapporteras inte i GA för Komin

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#12]
Sedan i morse rapporteras inte besök på Komin in till GA. malmo.se mfl fungerar som vanligt. Vill bara försäkra mig om att det inte är ett fel som vi själva har förorsakat.

**Comment by martent** [comment]
Senaste uppdateringen av Global Assets gjordes 28/9. Andra system som SV kan ha uppdaterats senare.

**Comment by olajoh1** [comment]
Rapporteras men med fördröjning flera  dagar i sträck för just komin
