### ISSUE TITLE
GA UAID: "None" visas för 10-20% av besökarna

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#14]
"None" visas för 10-20% av besökarna istället vald förvaltning i eventet Department

**Comment by martent** [comment]
`None` betyder att de inte valt någon förvaltning för sin "Grundprofil i Komin".

**Comment by olajoh1** [comment]
Man kan alltså logga in på Komin och använda intranätet fullt ut utan att välja förvaltning? Vad är fördelen med att ha det så?

**Comment by martent** [comment]
Man kan stanna vid att ha en inloggningsruta på Min sida eller sätta en annan sida som startsida i webbläsaren.
