### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#15]
![komin_typsnitt](https://cloud.githubusercontent.com/assets/6176181/18044389/e251ac42-6dcd-11e6-86d0-c584b27edace.PNG)

See header

**Comment by magnivar** [comment]
@susjon11 Säg till när det händer igen.

**Comment by magnivar** [comment]
Har att göra med IE-kompabilitetsvisning (IE-7)
Stänger tills någon säger till igen.
