### ISSUE TITLE
GA - redovisning på dubbla sidtitlar

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#5]
Sedan den 14 sept redovisas sidvisningar på dubbla sidtitlar. Bör åtgärdas snabbt så att felkällan försvinner.

![sbk_ex](https://cloud.githubusercontent.com/assets/6176181/10040326/cfe2d464-61da-11e5-9b2e-e6e5c8dd2d02.PNG)

**Comment by martent** [comment]
Fixat och utlagt externt och internt i produktion.

**Comment by olajoh1** [comment]
ok
