### ISSUE TITLE
Uppdatering av GA × 3

### ISSUE THREAD

**Issue by olajoh1** [malmostad/maintenance#9]
Lägg till enhanced link attribution och spåra noll-resultat i sök.

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution

[Conversion Analytics Dep Dive bonus pack.pdf](https://github.com/malmostad/maintenance/files/17359/Conversion.Analytics.Dep.Dive.bonus.pack.pdf)

Nytt event för komin, spåra organisatorisk tillhörighet enligt HR

**Comment by martent** [comment]
I test loggas nu förvaltning som händelsen HRDepartment på samma sätt som Department och WorkingField

Man får värdet när man gör ett av följande:
1.  Startar en ny webbläsarsession och går till Min sida (test)
2. Loggar ut och loggar in på min sida
3. Redigerar sin profil

**Comment by martent** [comment]
Nu loggas hela förvaltningsnamnet, typ "102 Stadskontoret".

**Comment by olajoh1** [comment]
Ser bra ut. Kan produktionssättas.

**Comment by martent** [comment]
Öppnar eftersom det finns fler en eller två aktiviteter till i ticketen.

**Comment by martent** [comment]
Enhanced link attribution är tillagt i koden för externa och interna test-webbar. Jag aktiverade det även i GA-administrationen för komin test respektive malmo.se test.

**Comment by martent** [comment]
Spåra noll-resultat kan man antingen logga som page views eller events. Jag föreslår det senare för att undvika att två page views registreras för sidan. I exemplet i den länkade PDF:en ovan så använder de dock page view-logging för noll-resultat.

@olajoh1, du får välja

**Comment by martent** [comment]
Vill du istället ha en mer generell översikt över antalet träffar kan vi logga ett event med namnet `SearchHits` och sätta Action till antalet träffar och Label till något annat eller lämna det tomt.

**Comment by olajoh1** [comment]
Håller med, event så att vi undviker dubbla page views.

Jag vill veta exakt hur många gånger ett sökbegrepp använts i de fall det har fått ett noll-resultat.

**Comment by martent** [comment]
Det finns två alternativ:

Endast nollresultat loggas:
Category: SearchNoResults
Action: söksträngen
Label: 0
Value: 1

Alla sökningar loggas med antal träffar (som kan vara 0):
Category: SearchHits
Action: söksträngen
Label: antal träffar
Value: 1

Jag är osäker på Value i båda fallen men jag har för mig att du brukar vilja ha det satt till 1 för att kunna summera upp.

Ni har inga testmiljöer för Sök men jag har triggat en lokalt till komin-test-statistiken. En sökning på "asdasdasdsaasdasd" har loggat båda varianter ovan samt en på "malmö" som har loggat SearchHits med Label 28258, vilket alltså är antalet träffar.

Jag har även aktiverat Search Tracking i admin för test-kontona. Men det har nog egentligen inte med detta att göra. Kategori kommer att loggas med Siteseekers ID:n som är en siffra. Du hittar den i den långa URL:en om du klickar på en kategori, t.ex. `cc[]=123` där kategorin då är 123 vilket kanske inte säger så mycket.

**Comment by martent** [comment]
Dessa tre features är deployade i produktion. Berör följande system som har uppdaterats:

1. Global Assets (intranet)
1. Global Assets (externa tjänst)
1. Min sida
1. Sök (intranet)
1. Sök (extern)

cc: @magnivar

**Comment by olajoh1** [comment]
ok
